# a docker-compose file to start both the frontend and backend
# use a caddy server to reverse proxy /api/* to the backend
# and everything else to the frontend

services:
  frontend:
    build:
      context: ui/
      args:
        - REACT_APP_API_BASE_URL=/api

  backend:
    build: backend/
    # mount .env file to backend container
    env_file:
      - backend/.env

  caddy:
    image: caddy:2.4.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
