# github actions to build and push docker images to ghcr

name: Build and push Docker images

on:
  push: # run on push to master
    branches:
      - main
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to ghcr.io (frontend)
      uses: docker/build-push-action@v2
      with:
        context: ./ui
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/costgpt-ui:latest

    - name: Build and push to ghcr.io (backend)
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/costgpt-api:latest

